# Generated by Django 4.2 on 2023-05-25 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('code', models.IntegerField(verbose_name='کد نویسنده')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر نویسنده')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('slug', models.SlugField(max_length=80, verbose_name='لینک نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان رویداد')),
                ('description', models.TextField(verbose_name='توضیحات رویداد')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر رویداد')),
                ('register_date', models.DateTimeField(verbose_name='تاریخ درج')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('duration', models.CharField(max_length=50, verbose_name='مدت زمان رویداد')),
                ('location', models.TextField(verbose_name='محل برگزاری رویداد')),
                ('organizer', models.CharField(max_length=50, verbose_name='برگزارکننده')),
                ('price', models.PositiveIntegerField(verbose_name='هزینه ثبت نام')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('slug', models.SlugField(max_length=90, verbose_name='لینک رویداد')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید')),
                ('slide_name', models.CharField(max_length=50, verbose_name='عنوان اسلاید')),
                ('title2', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن دوم')),
                ('title3', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن سوم')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('register_date', models.DateTimeField(verbose_name='تاریخ درج')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروز رسانی')),
                ('slug', models.SlugField(verbose_name='لینک ادرس')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satus_title', models.CharField(max_length=100, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصاویر رویداد')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pictures', to='main.events', verbose_name='رویداد')),
            ],
            options={
                'verbose_name': 'گالری تصویر رویداد',
                'verbose_name_plural': 'گالری تصاویر رویدادها',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.status', verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان مقاله')),
                ('content', models.TextField(verbose_name='متن اصلی')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('reading_time', models.CharField(max_length=50, verbose_name='مدت زمان مظالعه')),
                ('blog_field', models.CharField(max_length=50, verbose_name='حوزه مرتبط با مقاله')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('slug', models.SlugField(verbose_name='لینک مقاله')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_blogs', to='main.author', verbose_name='نویسنده مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
